/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/viki/catkin_ws/src/arbotix_ros/arbotix_msgs/srv/SetupChannel.srv
 *
 */


#ifndef ARBOTIX_MSGS_MESSAGE_SETUPCHANNEL_H
#define ARBOTIX_MSGS_MESSAGE_SETUPCHANNEL_H

#include <ros/service_traits.h>


#include <arbotix_msgs/SetupChannelRequest.h>
#include <arbotix_msgs/SetupChannelResponse.h>


namespace arbotix_msgs
{

struct SetupChannel
{

typedef SetupChannelRequest Request;
typedef SetupChannelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetupChannel
} // namespace arbotix_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arbotix_msgs::SetupChannel > {
  static const char* value()
  {
    return "c65e58d8b3b4d406126f6dc829a6011f";
  }

  static const char* value(const ::arbotix_msgs::SetupChannel&) { return value(); }
};

template<>
struct DataType< ::arbotix_msgs::SetupChannel > {
  static const char* value()
  {
    return "arbotix_msgs/SetupChannel";
  }

  static const char* value(const ::arbotix_msgs::SetupChannel&) { return value(); }
};


// service_traits::MD5Sum< ::arbotix_msgs::SetupChannelRequest> should match 
// service_traits::MD5Sum< ::arbotix_msgs::SetupChannel > 
template<>
struct MD5Sum< ::arbotix_msgs::SetupChannelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arbotix_msgs::SetupChannel >::value();
  }
  static const char* value(const ::arbotix_msgs::SetupChannelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arbotix_msgs::SetupChannelRequest> should match 
// service_traits::DataType< ::arbotix_msgs::SetupChannel > 
template<>
struct DataType< ::arbotix_msgs::SetupChannelRequest>
{
  static const char* value()
  {
    return DataType< ::arbotix_msgs::SetupChannel >::value();
  }
  static const char* value(const ::arbotix_msgs::SetupChannelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arbotix_msgs::SetupChannelResponse> should match 
// service_traits::MD5Sum< ::arbotix_msgs::SetupChannel > 
template<>
struct MD5Sum< ::arbotix_msgs::SetupChannelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arbotix_msgs::SetupChannel >::value();
  }
  static const char* value(const ::arbotix_msgs::SetupChannelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arbotix_msgs::SetupChannelResponse> should match 
// service_traits::DataType< ::arbotix_msgs::SetupChannel > 
template<>
struct DataType< ::arbotix_msgs::SetupChannelResponse>
{
  static const char* value()
  {
    return DataType< ::arbotix_msgs::SetupChannel >::value();
  }
  static const char* value(const ::arbotix_msgs::SetupChannelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARBOTIX_MSGS_MESSAGE_SETUPCHANNEL_H
