/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/viki/catkin_ws/src/rosR_demos/msg/Linearization.msg
 *
 */


#ifndef ROSR_DEMOS_MESSAGE_LINEARIZATION_H
#define ROSR_DEMOS_MESSAGE_LINEARIZATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosR_demos
{
template <class ContainerAllocator>
struct Linearization_
{
  typedef Linearization_<ContainerAllocator> Type;

  Linearization_()
    : dist(0.0)
    , volt(0.0)  {
    }
  Linearization_(const ContainerAllocator& _alloc)
    : dist(0.0)
    , volt(0.0)  {
    }



   typedef float _dist_type;
  _dist_type dist;

   typedef float _volt_type;
  _volt_type volt;




  typedef boost::shared_ptr< ::rosR_demos::Linearization_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosR_demos::Linearization_<ContainerAllocator> const> ConstPtr;

}; // struct Linearization_

typedef ::rosR_demos::Linearization_<std::allocator<void> > Linearization;

typedef boost::shared_ptr< ::rosR_demos::Linearization > LinearizationPtr;
typedef boost::shared_ptr< ::rosR_demos::Linearization const> LinearizationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosR_demos::Linearization_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosR_demos::Linearization_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosR_demos

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'rosR_demos': ['/home/viki/catkin_ws/src/rosR_demos/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosR_demos::Linearization_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosR_demos::Linearization_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosR_demos::Linearization_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosR_demos::Linearization_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosR_demos::Linearization_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosR_demos::Linearization_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosR_demos::Linearization_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f7dd391cdbb9d1f72822c152e8c430f";
  }

  static const char* value(const ::rosR_demos::Linearization_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f7dd391cdbb9d1fULL;
  static const uint64_t static_value2 = 0x72822c152e8c430fULL;
};

template<class ContainerAllocator>
struct DataType< ::rosR_demos::Linearization_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosR_demos/Linearization";
  }

  static const char* value(const ::rosR_demos::Linearization_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosR_demos::Linearization_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 dist\n\
float32 volt\n\
";
  }

  static const char* value(const ::rosR_demos::Linearization_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosR_demos::Linearization_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.dist);
      stream.next(m.volt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Linearization_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosR_demos::Linearization_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosR_demos::Linearization_<ContainerAllocator>& v)
  {
    s << indent << "dist: ";
    Printer<float>::stream(s, indent + "  ", v.dist);
    s << indent << "volt: ";
    Printer<float>::stream(s, indent + "  ", v.volt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSR_DEMOS_MESSAGE_LINEARIZATION_H
